# Sphragis RuboCop Configuration

require:
  - rubocop-rails
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

# Metrics
Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - '*.gemspec'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'test/**/*'

# Style
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'test/**/*'

# Rails
Rails/ApplicationController:
  Enabled: false

# Minitest
Minitest/MultipleAssertions:
  Max: 10
